apiVersion: v1
kind: Service
metadata:
     name: votingservice
     labels:
       app : voting_service
spec:
 type: NodePort
 ports:
    - targetPort: 80
      port: 80
      nodePort: 30011
 selector:
    app: frontpod
    type: votingpod