apiVersion: v1
kind: Pod
metadata:
    name: votingpod
    labels:	
     app: frontpod
     type: votingpod

spec:
  containers:
    - name: votingpod
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80